# mk - mk unix port from plan9
# Depends on ../lib9

TARG      = mk

OFILES    = arc.o archive.o bufblock.o env.o file.o graph.o job.o lex.o \
            main.o match.o mk.o parse.o recipe.o rc.o rule.o run.o sh.o \
            shell.o shprint.o symtab.o var.o varsub.o word.o unix.o
MANFILES  = mk.1

include ../std.mk

post-install:

pre-uninstall:

post-install:
