# grep - grep unix port from plan9
# Depends on ../lib9

TARG      = grep
OFILES    = y.tab.o main.o comp.o sub.o
YFILES    = grep.y
MANFILES  = grep.1

include ../yacc.mk

pre-uninstall:

post-install:
